/* PaneTrans landing — i18n dictionary.
 *
 * Keys are flat with dot-namespace for grep-ability. Values that contain
 * inline markup (<strong>, <a>, <code>, <em>) are referenced via
 * `data-i18n-html` so we can preserve the formatting across languages.
 *
 * Locale notes:
 * - "en" is the canonical source. Marketing pages are localized to zh/ja.
 * - Legal pages (terms / privacy / refund) include a small banner pointing
 *   non-en visitors back to the English version as the binding text. We
 *   still translate the legal copy for readability, but the binding-text
 *   note discharges the legal risk of translation drift.
 */
window.PANETRANS_I18N = {
  // ==========================================================================
  // English (canonical source).
  // ==========================================================================
  en: {
    // ---- Shared: nav + footer ----
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'footer.tagline': 'A pane of clarity on every frame.',
    'footer.product': 'Product',
    'footer.legal': 'Legal',
    'footer.contact': 'Contact',
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.refund': 'Refund Policy',
    'footer.copy': '© 2026 PaneTrans · Local AI translator for Chrome',
    'legal.canonicalNote': '',

    // ---- index.html ----
    'title.index': 'PaneTrans — Local-AI Chrome translator with live region monitoring',
    'meta.index': 'Drag a region on any web page and PaneTrans pins a glass popup with live translation that updates whenever the text changes. Powered by local AI — no cloud, no API keys, nothing leaves your browser.',
    'og.title.index': 'PaneTrans — A pane of clarity on every frame',
    'og.desc.index': 'Local-AI Chrome translator with continuous region monitoring.',
    'index.hero.h1': 'A pane of clarity on every frame.',
    'index.hero.lede': 'Drag a rectangle on any web page. PaneTrans pins a glass popup with <strong>live translation</strong> that updates the moment the text changes — live chat, video subtitles, ticker text, anywhere.',
    'index.hero.ledeSmall': 'All translation runs locally on your machine. No cloud. No API keys. Nothing leaves your browser.',
    'index.cta.seePricing': 'See pricing',
    'index.cta.howItWorks': 'How it works',
    'index.features.h2': 'What PaneTrans actually does',
    'index.feat1.h3': 'Drag, then watch.',
    'index.feat1.p': 'Right-click anywhere → <em>Translate Region</em> → drag a rectangle. A draggable popup shows the original and the translation side-by-side.',
    'index.feat2.h3': 'It keeps watching.',
    'index.feat2.p': 'A <code>MutationObserver</code> tracks the rectangle. Live chat lines, subtitle changes, ticker updates — the popup retranslates automatically. Like sticking a real-time subtitle strip onto any slice of the page.',
    'index.feat3.h3': 'Local AI, picked per task.',
    'index.feat3.p': 'Free tier: <strong>OPUS-MT</strong> (~160 MB / pair, real-time on WebGPU) and <strong>NLLB-200</strong> / <strong>M2M-100</strong> for higher quality. Pro tier: LLM-grade <strong>gpt-oss</strong> and <strong>Gemma 3</strong> for the most fluent output.',
    'index.trust.h2': 'Why anyone working with foreign-language content uses this',
    'index.trust.li1': '<strong>Zero data leaks.</strong> Translation models live in your browser cache. No request to a third-party server. Works offline once the model is downloaded.',
    'index.trust.li2': '<strong>Persistent, not single-shot.</strong> Most translators give you one translation and stop. PaneTrans pins a popup that follows the region until you close it.',
    'index.trust.li3': '<strong>Bilingual YouTube subtitles</strong> as a separate, opt-in feature for video learners.',
    'index.trust.li4': '<strong>Open architecture.</strong> Built on <a href="https://huggingface.co/docs/transformers.js" target="_blank" rel="noopener">Transformers.js</a> + <a href="https://huggingface.co/Xenova" target="_blank" rel="noopener">Xenova ONNX models</a>. You can audit the model list in <code>src/utils/languages.js</code>.',
    'index.ctaBand.h2': 'Ready to try it?',
    'index.ctaBand.p': 'The Free tier handles real-time translation for 10+ languages. Pro unlocks LLM-grade models for nuanced text.',
    'index.ctaBand.btn': 'Pricing',

    // ---- pricing.html ----
    'title.pricing': 'Pricing — PaneTrans',
    'meta.pricing': 'PaneTrans pricing: free real-time translation for 10+ languages, $14.99 lifetime or $2.99/mo for LLM-grade models.',
    'pricing.h1': 'Pricing',
    'pricing.lede': 'PaneTrans is free to use for real-time translation across 10+ languages. Pro unlocks larger LLM-based models for higher fluency.',
    'pricing.free.h2': 'Free',
    'pricing.free.priceSub': 'Forever',
    'pricing.free.li1': 'Drag-select region translation, continuous mode',
    'pricing.free.li2': 'YouTube bilingual subtitles',
    'pricing.free.li3': 'OPUS-MT (160 MB · real-time)',
    'pricing.free.li4': 'NLLB-200 (600 M params)',
    'pricing.free.li5': 'M2M-100 (418 M params)',
    'pricing.free.li6': '10+ languages, all language pairs',
    'pricing.free.li7': 'Local processing — no data leaves your browser',
    'pricing.free.cta': 'Install free',
    'pricing.lifetime.badge': 'Best value',
    'pricing.lifetime.h2': 'Lifetime',
    'pricing.lifetime.priceSub': 'One-time · forever',
    'pricing.lifetime.li1': 'Everything in Free',
    'pricing.lifetime.li2': '<strong>gpt-oss 1.5B</strong> — LLM-grade translation',
    'pricing.lifetime.li3': '<strong>Gemma 3 (4B)</strong> — context-aware fluency',
    'pricing.lifetime.li4': 'Priority email support',
    'pricing.lifetime.li5': 'All future model updates included',
    'pricing.lifetime.li6': 'Use on every browser you sign into',
    'pricing.lifetime.cta': 'Buy Lifetime — $14.99',
    'pricing.lifetime.note': '14-day refund, no questions asked.',
    'pricing.monthly.h2': 'Monthly',
    'pricing.monthly.priceSub': 'Cancel any time',
    'pricing.monthly.li1': 'Everything in Free',
    'pricing.monthly.li2': '<strong>gpt-oss 1.5B</strong> — LLM-grade translation',
    'pricing.monthly.li3': '<strong>Gemma 3 (4B)</strong> — context-aware fluency',
    'pricing.monthly.li4': 'Email support',
    'pricing.monthly.li5': 'Cancel any time, no contract',
    'pricing.monthly.cta': 'Subscribe — $2.99/mo',
    'pricing.monthly.note': '14-day refund on the first charge.',
    'pricing.faq.h2': 'FAQ',
    'pricing.faq.q1': 'Where does my payment go? Is my card data safe?',
    'pricing.faq.a1': 'Payments are processed by Paddle.com, a Merchant of Record handling tax and compliance in 200+ countries. PaneTrans never sees your card details — your data stays in Paddle\'s PCI-compliant infrastructure.',
    'pricing.faq.q2': 'What\'s the difference between Lifetime and Monthly?',
    'pricing.faq.a2': 'Lifetime is a single $14.99 payment for permanent access — including all future model updates. Monthly is $2.99/mo, cancellable any time. Lifetime breaks even after 5 months.',
    'pricing.faq.q3': 'Can I use Pro on multiple computers?',
    'pricing.faq.a3': 'Yes. After purchase you\'ll receive a license key by email. Activate it on as many of your personal browsers as you need.',
    'pricing.faq.q4': 'How do refunds work?',
    'pricing.faq.a4': '14-day no-questions-asked refund window. Email <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> with your purchase email and we\'ll process it. See the <a href="refund.html">full refund policy</a> for details.',
    'pricing.faq.q5': 'Does PaneTrans send any data to your servers?',
    'pricing.faq.a5': 'No translation data leaves your browser. The only network requests are: (1) downloading model files from Hugging Face the first time, (2) license validation against our license server. Both are documented in the <a href="privacy.html">privacy policy</a>.',

    // ---- support.html ----
    'title.support': 'Support — PaneTrans',
    'support.h1': 'Support',
    'support.metaDate': 'Last updated: 2026-05-18',
    'support.tldr': 'Need help? Email <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> with your Chrome version, the page URL where the problem happened, and (if relevant) your Paddle order ID. We reply within 2 business days.',
    'support.quickStart.h2': 'Quick start',
    'support.quickStart.li1': 'Install PaneTrans from the Chrome Web Store.',
    'support.quickStart.li2': 'Open any web page with text you want translated.',
    'support.quickStart.li3': 'Right-click → <strong>Translate Region</strong>, or click the PaneTrans toolbar icon → <strong>Drag a region</strong>.',
    'support.quickStart.li4': 'Drag a rectangle around the text. A draggable popup appears with the original and translation side-by-side.',
    'support.quickStart.li5': 'The popup keeps re-translating as the underlying text changes — close it with the × when you\'re done.',
    'support.issues.h2': 'Common issues',
    'support.issue.slowFirst.h3': 'The first translation is slow.',
    'support.issue.slowFirst.p': 'The first time you pick a translation model, PaneTrans downloads it from Hugging Face\'s CDN (around 160 MB for OPUS-MT, larger for NLLB / M2M / Gemma). The model is then cached in your browser, so subsequent translations are instant. You can pre-download models from the toolbar popup → <strong>Models</strong>.',
    'support.issue.noTrans.h3': 'The popup shows the original text but no translation.',
    'support.issue.noTrans.p': 'Usually means the selected model is still downloading or your machine doesn\'t have WebGPU. Open the toolbar popup → <strong>Models</strong> and check the download progress. If WebGPU is unavailable, PaneTrans falls back to WASM (slower but works on any machine).',
    'support.issue.noMenu.h3': '"Translate Region" isn\'t in the right-click menu.',
    'support.issue.noMenu.p': 'Make sure the extension is enabled at <code>chrome://extensions</code>. If you just installed it, reload the page once — the context-menu item is registered when the page loads.',
    'support.issue.noYt.h3': 'YouTube bilingual subtitles aren\'t appearing.',
    'support.issue.noYt.p': 'Open the toolbar popup, switch the <strong>YouTube subtitles</strong> toggle on, and reload the YouTube tab. The feature only activates on <code>youtube.com/watch?v=…</code> pages.',
    'support.issue.noOcr.h3': 'OCR (text in images / videos) isn\'t working.',
    'support.issue.noOcr.p': 'PaneTrans uses Tesseract.js for OCR; it downloads language data from <code>tessdata.projectnaptha.com</code> on first use. If your network blocks that host, OCR will fail. The error message in the popup tells you which language data is missing.',
    'support.license.h2': 'License keys (Pro)',
    'support.license.notArrived.h3': 'I bought Pro but my license key didn\'t arrive.',
    'support.license.notArrived.p': 'Check your spam folder for the receipt from Paddle. If it\'s not there, email us with the address you used at checkout and we\'ll resend the key.',
    'support.license.activate.h3': 'Activating the key.',
    'support.license.activate.p': 'Open the toolbar popup → <strong>Upgrade</strong> → paste the key → <strong>Activate</strong>. The Pro models (gpt-oss, Gemma 3) become available in the model picker once activation succeeds.',
    'support.license.multi.h3': 'Using Pro on multiple browsers.',
    'support.license.multi.p': 'Your key activates on multiple browsers — sign in with the same Chrome / Edge / Brave profile and activate again on each one. If you hit the activation limit, email us and we\'ll reset it.',
    'support.license.refund.h3': 'Refunds.',
    'support.license.refund.p': '14-day no-questions-asked. See the <a href="refund.html">Refund Policy</a> for the exact procedure.',
    'support.contact.h2': 'Contact',
    'support.contact.intro': 'Email: <a href="mailto:hi@julineshang.win">hi@julineshang.win</a><br>When you write, please include:',
    'support.contact.li1': 'Your Chrome / Edge / Brave version (from <code>chrome://version</code>)',
    'support.contact.li2': 'The URL of the page where the problem happened (if web-related)',
    'support.contact.li3': 'A screenshot of the popup or any error message',
    'support.contact.li4': 'Your Paddle order ID (if it\'s a license / billing question)',
    'support.policies.h2': 'Privacy & policies',

    // ---- terms.html ----
    'title.terms': 'Terms of Service — PaneTrans',
    'terms.h1': 'Terms of Service',
    'terms.effective': 'Effective date: 2026-04-25 · Last updated: 2026-04-25',
    'terms.h2.1': '1. Acceptance',
    'terms.p.1': 'By installing or using the PaneTrans browser extension ("Service"), you agree to these Terms. If you do not agree, do not use the Service.',
    'terms.h2.2': '2. The Service',
    'terms.p.2': 'PaneTrans is a Chrome browser extension that performs translation of web content using local AI models running in the user\'s browser. Core translation features run entirely on the user\'s device.',
    'terms.h2.3': '3. License',
    'terms.p.3': 'Subject to your compliance with these Terms (and, for paid tiers, payment of the applicable fee), we grant you a personal, non-exclusive, non-transferable, revocable license to install and use the Service for non-commercial personal use, or for use within your own work product as an individual professional.',
    'terms.h2.4': '4. Paid features',
    'terms.p.4a': 'Some features (e.g. LLM-grade translation models) require a paid license. Paid licenses are sold under one of the following plans:',
    'terms.li.4a': '<strong>Lifetime:</strong> a one-time payment of US$14.99 for permanent access.',
    'terms.li.4b': '<strong>Monthly:</strong> a recurring subscription of US$2.99/month, cancellable at any time before the next renewal.',
    'terms.p.4b': 'Payments are processed by Paddle.com Market Limited ("Paddle"), the Merchant of Record. Paddle\'s terms apply to the transaction itself in addition to ours.',
    'terms.h2.5': '5. License keys and devices',
    'terms.p.5': 'You will receive a license key by email upon successful payment. You may activate this key on any browser you personally use. Sharing your license key with others is prohibited and may result in revocation of access without refund.',
    'terms.h2.6': '6. Refunds',
    'terms.p.6': 'You may request a full refund within 14 days of purchase by emailing <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> from the address used for payment. See the <a href="refund.html">Refund Policy</a> for full details.',
    'terms.h2.7': '7. Acceptable use',
    'terms.p.7a': 'You agree not to use the Service to:',
    'terms.li.7a': 'Translate content you do not have the right to access;',
    'terms.li.7b': 'Reverse-engineer, modify, or redistribute the extension\'s code in violation of its open-source notices;',
    'terms.li.7c': 'Bypass the license-key validation system or pirate the paid tier;',
    'terms.li.7d': 'Run the Service on infrastructure that re-sells PaneTrans translation as a commercial API or batch service.',
    'terms.h2.8': '8. Models and third parties',
    'terms.p.8': 'Translation models used by the Service are downloaded from Hugging Face on first use. You are responsible for complying with the licenses of those models (each model\'s license is shown in the popup UI). PaneTrans is not affiliated with Hugging Face, OpenAI, Google, or any model author.',
    'terms.h2.9': '9. Disclaimer',
    'terms.p.9': 'THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE", WITHOUT WARRANTY OF ANY KIND. TRANSLATION QUALITY IS NOT GUARANTEED. We do not warrant that translations will be accurate, complete, or fit for any particular purpose. You should not rely on PaneTrans alone for legal, medical, financial, or other consequential translations.',
    'terms.h2.10': '10. Limitation of liability',
    'terms.p.10': 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR AGGREGATE LIABILITY ARISING FROM OR RELATING TO THE SERVICE IS LIMITED TO THE AMOUNT YOU PAID FOR THE SERVICE IN THE TWELVE MONTHS PRECEDING THE CLAIM. WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES.',
    'terms.h2.11': '11. Termination',
    'terms.p.11': 'We may suspend or revoke your license if you breach these Terms (notably the acceptable-use clause). You may stop using the Service at any time by uninstalling the extension.',
    'terms.h2.12': '12. Changes',
    'terms.p.12': 'We may update these Terms. We will post the updated version on this page and update the "Last updated" date. Material changes will be notified via the extension popup or by email if you have an active license.',
    'terms.h2.13': '13. Governing law',
    'terms.p.13': 'These Terms are governed by the laws of the jurisdiction of the seller\'s place of residence (currently the People\'s Republic of China, Hong Kong SAR), without regard to conflict-of-law rules. Disputes will be resolved in the competent courts of that jurisdiction.',
    'terms.h2.14': '14. Contact',
    'terms.p.14': 'Questions or notices: <a href="mailto:hi@julineshang.win">hi@julineshang.win</a>.',

    // ---- privacy.html ----
    'title.privacy': 'Privacy Policy — PaneTrans',
    'privacy.h1': 'Privacy Policy',
    'privacy.effective': 'Effective date: 2026-04-25 · Last updated: 2026-04-25',
    'privacy.tldr': '<strong>TL;DR.</strong> PaneTrans does not collect, transmit, or store the text you translate. Translation happens entirely inside your browser. The only network requests the extension makes are: (1) downloading model files from Hugging Face the first time you use a model, and (2) validating your license key against our license server when you activate a paid plan.',
    'privacy.h2.1': '1. Who we are',
    'privacy.p.1': '"PaneTrans" is operated as an individual project by the developer registered at <a href="mailto:hi@julineshang.win">hi@julineshang.win</a>. This policy describes how we treat the information you provide when you install, use, or purchase the PaneTrans extension.',
    'privacy.h2.2': '2. What runs locally vs. on a server',
    'privacy.p.2': 'The core translation pipeline — text extraction, model inference, OCR (optical character recognition for video frames), and rendering of the translation popup — runs entirely inside your browser using <a href="https://huggingface.co/docs/transformers.js" target="_blank" rel="noopener">Transformers.js</a> and ONNX models. <strong>The text you translate never leaves your device.</strong>',
    'privacy.h2.3': '3. Network requests we do make',
    'privacy.li.3a': '<strong>Model downloads.</strong> When you select a translation model for the first time, the extension downloads its weight files from Hugging Face\'s CDN (huggingface.co / hf.co) and caches them in your browser\'s storage for offline use. Hugging Face may log your IP address as part of the standard HTTP request.',
    'privacy.li.3b': '<strong>OCR worker.</strong> When falling back to OCR for image/video content, the extension downloads Tesseract.js language data from <code>tessdata.projectnaptha.com</code> and a small WASM binary from <code>cdn.jsdelivr.net</code>. These are static asset CDNs.',
    'privacy.li.3c': '<strong>License validation (paid users only).</strong> When you paste a license key into the popup, the extension sends the key (and only the key) to our license server. The server returns whether the key is valid and what plan it belongs to. We do not log the IP address of these requests for longer than 7 days; we do log the license-key ID and timestamp for fraud detection.',
    'privacy.h2.4': '4. What we do NOT collect',
    'privacy.li.4a': 'The text you select for translation.',
    'privacy.li.4b': 'The pages you visit.',
    'privacy.li.4c': 'Your browsing history.',
    'privacy.li.4d': 'Any analytics or telemetry. There is no Google Analytics, no Sentry, no PostHog inside the extension.',
    'privacy.li.4e': 'Form data, passwords, cookies, or any DOM content outside of the rectangle you explicitly drag.',
    'privacy.h2.5': '5. Payment data',
    'privacy.p.5a': 'If you purchase a paid plan, payment is processed by <strong>Paddle.com Market Limited</strong>, our Merchant of Record. Paddle handles your card details, billing address, and tax information directly — we never see or store your card. Paddle is GDPR- and CCPA-compliant. See <a href="https://www.paddle.com/legal/privacy" target="_blank" rel="noopener">Paddle\'s privacy policy</a>.',
    'privacy.p.5b': 'We receive from Paddle: your email address, license-key identifier, plan, and purchase date. We use this only to (a) deliver and validate your license key, (b) provide refunds and support, (c) keep tax records as required by law.',
    'privacy.h2.6': '6. Storage on your device',
    'privacy.p.6a': 'The extension stores in <code>chrome.storage.local</code> (your browser, your machine):',
    'privacy.li.6a': 'Your UI preferences (selected language, model, font size).',
    'privacy.li.6b': 'Your license key, if you\'ve activated one, and the cached "last validated at" timestamp (used for offline grace).',
    'privacy.li.6c': 'The download progress / readiness state of each translation model.',
    'privacy.p.6b': 'You can clear this at any time by uninstalling the extension or clearing the extension\'s storage from <code>chrome://extensions</code>.',
    'privacy.h2.7': '7. Permissions and why we ask',
    'privacy.li.7a': '<strong><code>&lt;all_urls&gt;</code></strong>: required so the region-translate feature works on any website you choose. The extension does not auto-read any page; it only acts on regions you explicitly drag.',
    'privacy.li.7b': '<strong><code>storage</code></strong>: to remember your settings and license between sessions.',
    'privacy.li.7c': '<strong><code>activeTab</code> + <code>scripting</code></strong>: to inject the region-select overlay when you click the extension button.',
    'privacy.li.7d': '<strong><code>contextMenus</code></strong>: to add the "Translate Region" right-click menu item.',
    'privacy.li.7e': '<strong><code>offscreen</code></strong>: required by Chrome MV3 to run AI inference outside the service worker (which has memory limits incompatible with model files).',
    'privacy.h2.8': '8. Children',
    'privacy.p.8': 'PaneTrans is not directed at children under 13. We do not knowingly collect personal data from children.',
    'privacy.h2.9': '9. Your rights (GDPR / CCPA)',
    'privacy.p.9': 'If you are an EU/UK resident, you have the right to access, rectify, delete, and export the personal data we hold about you (essentially: your email and license key). California residents have analogous rights under the CCPA. Email <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> with your purchase email to exercise these rights.',
    'privacy.h2.10': '10. Changes',
    'privacy.p.10': 'We will post any updated version of this policy on this page and update the "Last updated" date. If a change materially affects your rights, we will notify active license-holders by email.',
    'privacy.h2.11': '11. Contact',
    'privacy.p.11': 'Privacy or data-protection questions: <a href="mailto:hi@julineshang.win">hi@julineshang.win</a>.',

    // ---- refund.html ----
    'title.refund': 'Refund Policy — PaneTrans',
    'refund.h1': 'Refund Policy',
    'refund.effective': 'Effective date: 2026-04-25 · Last updated: 2026-04-25',
    'refund.tldr': '<strong>14 days, no questions asked.</strong> If PaneTrans isn\'t right for you within 14 days of purchase, email <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> from the address you used to pay and we\'ll refund you in full.',
    'refund.h2.1': '1. Who is eligible',
    'refund.p.1': 'Anyone who purchased a paid PaneTrans plan (Lifetime or Monthly) within the last 14 days, regardless of how much you used the Pro features.',
    'refund.h2.2': '2. How to request',
    'refund.li.2a': 'Email <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> from the email address you used at checkout.',
    'refund.li.2b': 'Include your Paddle order ID if you have it (it\'s in the receipt email Paddle sent you), or the date and approximate amount of the purchase.',
    'refund.li.2c': 'You don\'t need to give a reason. We won\'t argue.',
    'refund.h2.3': '3. How long it takes',
    'refund.p.3': 'We aim to acknowledge your email within 2 business days and process the refund within 5 business days. The refund itself is issued by Paddle (our Merchant of Record) and lands back on your original payment method, typically within 5–10 business days after that.',
    'refund.h2.4': '4. What happens to your license',
    'refund.p.4': 'Once the refund is issued, your license key is revoked. The free tier of PaneTrans continues to work normally — you\'ll just lose access to the LLM-grade Pro models.',
    'refund.h2.5': '5. Subscription cancellations (Monthly plan)',
    'refund.p.5': 'You can cancel a Monthly subscription at any time directly from the Paddle customer portal (link is in your receipt email). Cancelling stops future renewals immediately. The current paid period continues until its expiry date — there is no proration on cancellation.',
    'refund.h2.6': '6. Renewal refunds',
    'refund.p.6': 'If a Monthly subscription auto-renewed and you didn\'t intend it to, contact us within 14 days of the renewal charge and we\'ll refund that charge under the same 14-day window above.',
    'refund.h2.7': '7. Outside the 14-day window',
    'refund.p.7': 'Refunds outside the 14-day window are evaluated case-by-case. We\'re reasonable; if PaneTrans broke after a Chrome update or the Pro models stopped working through no fault of yours, email us and we\'ll sort it out.',
    'refund.h2.8': '8. Chargebacks',
    'refund.p.8': 'Please email us before initiating a chargeback with your bank. Chargebacks cost both of us money and time, and we\'d rather just refund you. Repeated chargebacks may lead to license revocation without further refund.',
    'refund.h2.9': '9. Contact',
    'refund.p.9': 'Refund requests and questions: <a href="mailto:hi@julineshang.win">hi@julineshang.win</a>.',
  },

  // ==========================================================================
  // 简体中文 (zh-CN)
  // ==========================================================================
  zh: {
    // ---- Shared ----
    'nav.features': '功能',
    'nav.pricing': '定价',
    'footer.tagline': '为画面里的每一帧字，开一扇清晰的窗。',
    'footer.product': '产品',
    'footer.legal': '法律条款',
    'footer.contact': '联系我们',
    'footer.legal.terms': '服务条款',
    'footer.legal.privacy': '隐私政策',
    'footer.legal.refund': '退款政策',
    'footer.copy': '© 2026 PaneTrans · Chrome 本地 AI 翻译扩展',
    'legal.canonicalNote': '本中文版仅作便利阅读，发生争议时以 <a href="?lang=en">英文版本</a> 为准。',

    // ---- index ----
    'title.index': 'PaneTrans — 本地 AI、画面实时翻译的 Chrome 扩展',
    'meta.index': '在任意网页拉一个框，PaneTrans 钉住一个磨砂浮窗，文字一变就重新翻译。本地 AI 运行 —— 不联网、不要 key、不离开浏览器。',
    'og.title.index': 'PaneTrans — 为每一帧画面开一扇清晰的窗',
    'og.desc.index': '本地 AI Chrome 翻译扩展，区域持续监听。',
    'index.hero.h1': '为画面里的每一行字，开一扇清晰的窗。',
    'index.hero.lede': '在任意网页拉一个框。PaneTrans 钉住一个磨砂浮窗，<strong>实时翻译</strong> —— 文字一变就重新翻译。直播聊天、视频字幕、滚动条幅，哪儿都行。',
    'index.hero.ledeSmall': '所有翻译都在你本机跑。不联网、不要 API key、数据不离开浏览器。',
    'index.cta.seePricing': '查看定价',
    'index.cta.howItWorks': '工作原理',
    'index.features.h2': 'PaneTrans 到底能做什么',
    'index.feat1.h3': '画一框，盯住它。',
    'index.feat1.p': '右键任意位置 → <em>翻译区域</em> → 拖出一个矩形。可拖动浮窗左右并列展示原文和译文。',
    'index.feat2.h3': '它一直在盯。',
    'index.feat2.p': '一个 <code>MutationObserver</code> 跟着这个矩形跑。直播聊天、字幕变化、行情滚动 —— 浮窗自动重新翻译。等于把一条实时字幕条贴在网页任意位置。',
    'index.feat3.h3': '本地 AI，按任务挑模型。',
    'index.feat3.p': '免费档：<strong>OPUS-MT</strong>（每对约 160 MB，WebGPU 实时）和 <strong>NLLB-200</strong> / <strong>M2M-100</strong> 提高质量。Pro 档：大模型级别的 <strong>gpt-oss</strong> 和 <strong>Gemma 3</strong> 输出更流畅。',
    'index.trust.h2': '为什么靠外文内容学习/工作的人都装它',
    'index.trust.li1': '<strong>零数据泄漏。</strong>翻译模型缓存在你的浏览器里。不发请求到第三方服务器。模型下载一次后可离线使用。',
    'index.trust.li2': '<strong>持续监听，不是一次性。</strong>大部分翻译工具点一次给你一个结果就完事。PaneTrans 把浮窗钉在区域上，直到你自己关闭。',
    'index.trust.li3': '<strong>YouTube 双语字幕</strong>作为独立可选功能，专门服务给视频学习者。',
    'index.trust.li4': '<strong>架构开放。</strong>基于 <a href="https://huggingface.co/docs/transformers.js" target="_blank" rel="noopener">Transformers.js</a> + <a href="https://huggingface.co/Xenova" target="_blank" rel="noopener">Xenova ONNX 模型</a>。模型列表你可以在 <code>src/utils/languages.js</code> 里自己审查。',
    'index.ctaBand.h2': '想试试吗？',
    'index.ctaBand.p': '免费档支持 10+ 语言实时翻译。Pro 档解锁大模型级别的精细译文。',
    'index.ctaBand.btn': '定价',

    // ---- pricing ----
    'title.pricing': '定价 — PaneTrans',
    'meta.pricing': 'PaneTrans 定价：10+ 语言实时翻译永久免费，$14.99 终身买断或 $2.99/月解锁大模型档。',
    'pricing.h1': '定价',
    'pricing.lede': 'PaneTrans 免费即可使用 10+ 语言实时翻译。Pro 档解锁更大的 LLM 模型，让译文更流畅。',
    'pricing.free.h2': '免费版',
    'pricing.free.priceSub': '永久免费',
    'pricing.free.li1': '区域选择翻译，持续监听模式',
    'pricing.free.li2': 'YouTube 双语字幕',
    'pricing.free.li3': 'OPUS-MT（160 MB · 实时）',
    'pricing.free.li4': 'NLLB-200（6 亿参数）',
    'pricing.free.li5': 'M2M-100（4.18 亿参数）',
    'pricing.free.li6': '10+ 语言，全语种互译',
    'pricing.free.li7': '本地处理 —— 数据不离开你的浏览器',
    'pricing.free.cta': '免费安装',
    'pricing.lifetime.badge': '最划算',
    'pricing.lifetime.h2': '终身版',
    'pricing.lifetime.priceSub': '一次付费 · 永久使用',
    'pricing.lifetime.li1': '免费版所有功能',
    'pricing.lifetime.li2': '<strong>gpt-oss 1.5B</strong> —— 大模型级翻译',
    'pricing.lifetime.li3': '<strong>Gemma 3（4B）</strong> —— 上下文感知，更流畅',
    'pricing.lifetime.li4': '邮件优先支持',
    'pricing.lifetime.li5': '后续所有模型更新均包含',
    'pricing.lifetime.li6': '可在你登录的任何浏览器上使用',
    'pricing.lifetime.cta': '终身买断 — $14.99',
    'pricing.lifetime.note': '14 天无理由退款。',
    'pricing.monthly.h2': '月付',
    'pricing.monthly.priceSub': '随时取消',
    'pricing.monthly.li1': '免费版所有功能',
    'pricing.monthly.li2': '<strong>gpt-oss 1.5B</strong> —— 大模型级翻译',
    'pricing.monthly.li3': '<strong>Gemma 3（4B）</strong> —— 上下文感知，更流畅',
    'pricing.monthly.li4': '邮件支持',
    'pricing.monthly.li5': '随时取消，无合约',
    'pricing.monthly.cta': '订阅 — $2.99/月',
    'pricing.monthly.note': '首次扣款 14 天内可全额退款。',
    'pricing.faq.h2': '常见问题',
    'pricing.faq.q1': '我的钱给谁了？卡信息安全吗？',
    'pricing.faq.a1': '付款由 Paddle.com 处理，他们是 Merchant of Record（注册商户），负责 200+ 国家的税务和合规。PaneTrans 看不到你的卡号 —— 数据全程在 Paddle 的 PCI 合规系统里。',
    'pricing.faq.q2': '终身版和月付有什么区别？',
    'pricing.faq.a2': '终身版一次性付 $14.99 永久使用 —— 包含后续所有模型更新。月付 $2.99/月，随时可取消。终身版 5 个月就回本。',
    'pricing.faq.q3': 'Pro 能在多台电脑上用吗？',
    'pricing.faq.a3': '可以。付款后你会收到一个授权 key 邮件。在你自己用的浏览器上想激活几个就激活几个。',
    'pricing.faq.q4': '怎么退款？',
    'pricing.faq.a4': '14 天无理由退款窗口。用付款时的邮箱发邮件到 <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> 即可处理。详细见 <a href="refund.html">退款政策</a>。',
    'pricing.faq.q5': 'PaneTrans 会把数据发回你们服务器吗？',
    'pricing.faq.a5': '翻译数据不离开浏览器。仅有的网络请求是：(1) 首次使用模型时从 Hugging Face 下载模型，(2) 激活授权时跟我们的 license 服务器校验。两条均在 <a href="privacy.html">隐私政策</a> 里有说明。',

    // ---- support ----
    'title.support': '帮助中心 — PaneTrans',
    'support.h1': '帮助中心',
    'support.metaDate': '最后更新：2026-05-18',
    'support.tldr': '需要帮助？发邮件到 <a href="mailto:hi@julineshang.win">hi@julineshang.win</a>，附上你的 Chrome 版本、出问题的页面 URL，以及（如相关）你的 Paddle 订单号。两个工作日内回复。',
    'support.quickStart.h2': '快速上手',
    'support.quickStart.li1': '在 Chrome 应用商店安装 PaneTrans。',
    'support.quickStart.li2': '打开任意网页，找你想翻译的文字。',
    'support.quickStart.li3': '右键 → <strong>翻译区域</strong>，或者点扩展工具栏图标 → <strong>拖动选区</strong>。',
    'support.quickStart.li4': '在文字四周拉出一个矩形。会弹出一个可拖动的浮窗，原文 + 译文左右并列。',
    'support.quickStart.li5': '只要底下文字变了，浮窗就持续重新翻译 —— 看完点右上 × 关掉。',
    'support.issues.h2': '常见问题',
    'support.issue.slowFirst.h3': '第一次翻译怎么这么慢？',
    'support.issue.slowFirst.p': '第一次选用某个翻译模型时，PaneTrans 会从 Hugging Face CDN 下载（OPUS-MT 大约 160 MB，NLLB / M2M / Gemma 更大）。模型下载完会缓存在浏览器里，后续翻译就秒回。也可以在工具栏弹窗 → <strong>模型</strong> 里提前下载。',
    'support.issue.noTrans.h3': '浮窗只显示原文，没显示译文。',
    'support.issue.noTrans.p': '通常是选中的模型还在下载，或者你的机器没有 WebGPU。打开工具栏弹窗 → <strong>模型</strong> 看下载进度。没有 WebGPU 时，PaneTrans 会自动回落到 WASM（慢一点但兼容所有机器）。',
    'support.issue.noMenu.h3': '右键菜单里没有"翻译区域"。',
    'support.issue.noMenu.p': '确认 <code>chrome://extensions</code> 里扩展是启用状态。如果是刚装的，刷新一下页面 —— 右键菜单项是页面加载时注册的。',
    'support.issue.noYt.h3': 'YouTube 双语字幕没出现。',
    'support.issue.noYt.p': '打开工具栏弹窗，把 <strong>YouTube 字幕</strong> 开关打开，然后刷新 YouTube 标签页。该功能仅在 <code>youtube.com/watch?v=…</code> 页面上生效。',
    'support.issue.noOcr.h3': '图片/视频里的 OCR 不工作。',
    'support.issue.noOcr.p': 'PaneTrans 用 Tesseract.js 做 OCR，首次使用会从 <code>tessdata.projectnaptha.com</code> 下载语言数据。如果你的网络封了这个域，OCR 会失败。浮窗里的错误提示会告诉你缺哪个语言包。',
    'support.license.h2': '授权 Key（Pro）',
    'support.license.notArrived.h3': '买了 Pro 但没收到授权 key。',
    'support.license.notArrived.p': '先看下垃圾箱里有没有 Paddle 发的收据。要是没有，用付款时的邮箱发信给我们，我们重新补发。',
    'support.license.activate.h3': '怎么激活 Key。',
    'support.license.activate.p': '打开工具栏弹窗 → <strong>升级</strong> → 粘贴 key → <strong>激活</strong>。激活成功后，模型选择器里就会出现 Pro 模型（gpt-oss、Gemma 3）。',
    'support.license.multi.h3': '多浏览器使用 Pro。',
    'support.license.multi.p': '你的 key 可以激活多台浏览器 —— 在同一个 Chrome / Edge / Brave 配置下登录后，每台都激活一次即可。激活数到上限时给我们发邮件，我们重置。',
    'support.license.refund.h3': '退款。',
    'support.license.refund.p': '14 天无理由退款。具体流程见 <a href="refund.html">退款政策</a>。',
    'support.contact.h2': '联系我们',
    'support.contact.intro': '邮箱：<a href="mailto:hi@julineshang.win">hi@julineshang.win</a><br>发邮件时麻烦带上：',
    'support.contact.li1': '你的 Chrome / Edge / Brave 版本（在 <code>chrome://version</code> 看）',
    'support.contact.li2': '出问题的页面 URL（如果是网页相关问题）',
    'support.contact.li3': '弹窗或错误信息截图',
    'support.contact.li4': '你的 Paddle 订单号（如果是授权 / 计费问题）',
    'support.policies.h2': '隐私与政策',

    // ---- terms ----
    'title.terms': '服务条款 — PaneTrans',
    'terms.h1': '服务条款',
    'terms.effective': '生效日期：2026-04-25 · 最后更新：2026-04-25',
    'terms.h2.1': '1. 接受',
    'terms.p.1': '安装或使用 PaneTrans 浏览器扩展（"服务"）即表示你接受本条款。如不同意，请勿使用本服务。',
    'terms.h2.2': '2. 关于本服务',
    'terms.p.2': 'PaneTrans 是一款 Chrome 浏览器扩展，使用本地 AI 模型在用户浏览器内翻译网页内容。核心翻译功能完全在用户设备上运行。',
    'terms.h2.3': '3. 许可',
    'terms.p.3': '在你遵守本条款（及付费档下支付相应费用）的前提下，我们授予你个人、非独占、不可转让、可撤销的许可，用于个人非商业使用，或作为个人专业人士在自身工作产物中使用。',
    'terms.h2.4': '4. 付费功能',
    'terms.p.4a': '部分功能（如大模型级翻译）需要付费授权。付费授权按以下两种方案出售：',
    'terms.li.4a': '<strong>终身版：</strong>一次性付款 US$14.99，永久使用。',
    'terms.li.4b': '<strong>月付：</strong>循环订阅 US$2.99/月，可在下次续费前的任意时刻取消。',
    'terms.p.4b': '付款由 Paddle.com Market Limited（"Paddle"）作为 Merchant of Record 处理。Paddle 的条款适用于交易本身，本条款同时适用。',
    'terms.h2.5': '5. 授权 Key 与设备',
    'terms.p.5': '付款成功后你会通过邮件收到一个授权 key。可在你个人使用的任何浏览器上激活。禁止将 key 分享给他人，否则可能导致访问被撤销，不予退款。',
    'terms.h2.6': '6. 退款',
    'terms.p.6': '自购买之日起 14 天内可发邮件到 <a href="mailto:hi@julineshang.win">hi@julineshang.win</a>（使用付款邮箱）申请全额退款。详细见 <a href="refund.html">退款政策</a>。',
    'terms.h2.7': '7. 可接受的使用',
    'terms.p.7a': '你同意不将本服务用于：',
    'terms.li.7a': '翻译你无权访问的内容；',
    'terms.li.7b': '违反开源声明地反向工程、修改或再分发扩展代码；',
    'terms.li.7c': '绕过授权 key 校验系统或盗版付费档；',
    'terms.li.7d': '在某种基础设施上运行本服务以将 PaneTrans 翻译转售为商用 API 或批处理服务。',
    'terms.h2.8': '8. 模型与第三方',
    'terms.p.8': '本服务使用的翻译模型在首次使用时从 Hugging Face 下载。你有义务遵守这些模型的许可（每个模型的许可均会在弹窗 UI 中显示）。PaneTrans 与 Hugging Face、OpenAI、Google 或任何模型作者均无关联。',
    'terms.h2.9': '9. 免责声明',
    'terms.p.9': '本服务按"现状"和"现有"提供，不附带任何形式的担保。翻译质量不保证。我们不保证翻译准确、完整或适合任何特定用途。请勿仅依赖 PaneTrans 用于法律、医疗、金融或其他具有重大后果的翻译。',
    'terms.h2.10': '10. 责任限制',
    'terms.p.10': '在法律允许的最大范围内，我们因本服务或与本服务相关而产生的合计责任，以你在主张前 12 个月内为本服务支付的金额为上限。我们不对任何间接、附带或衍生损害承担责任。',
    'terms.h2.11': '11. 终止',
    'terms.p.11': '如你违反本条款（尤其是可接受使用条款），我们可能暂停或撤销你的许可。你可随时通过卸载扩展停止使用本服务。',
    'terms.h2.12': '12. 变更',
    'terms.p.12': '我们可能更新本条款。更新后的版本会发布在本页面并更新"最后更新"日期。重大变更将通过扩展弹窗通知，或在你持有有效授权时通过邮件通知。',
    'terms.h2.13': '13. 适用法律',
    'terms.p.13': '本条款受卖方居住地（目前为中华人民共和国香港特别行政区）法律管辖，不考虑法律冲突规则。争议由该司法管辖区有管辖权的法院解决。',
    'terms.h2.14': '14. 联系',
    'terms.p.14': '问题或通知：<a href="mailto:hi@julineshang.win">hi@julineshang.win</a>。',

    // ---- privacy ----
    'title.privacy': '隐私政策 — PaneTrans',
    'privacy.h1': '隐私政策',
    'privacy.effective': '生效日期：2026-04-25 · 最后更新：2026-04-25',
    'privacy.tldr': '<strong>简述：</strong>PaneTrans 不收集、不传输、不存储你翻译的文字。翻译完全在你浏览器里完成。扩展只发两类网络请求：(1) 首次使用模型时从 Hugging Face 下载模型文件，(2) 激活付费档时把授权 key 提交给我们的 license 服务器校验。',
    'privacy.h2.1': '1. 我们是谁',
    'privacy.p.1': '"PaneTrans" 由注册邮箱为 <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> 的开发者以个人项目方式运营。本政策说明在你安装、使用或购买 PaneTrans 扩展时，我们如何处理你提供的信息。',
    'privacy.h2.2': '2. 哪些在本地、哪些在服务端',
    'privacy.p.2': '核心翻译流水线 —— 文字提取、模型推理、OCR（视频帧的光学字符识别）、翻译浮窗渲染 —— 完全在你浏览器内通过 <a href="https://huggingface.co/docs/transformers.js" target="_blank" rel="noopener">Transformers.js</a> 和 ONNX 模型运行。<strong>你翻译的文字永远不离开你的设备。</strong>',
    'privacy.h2.3': '3. 我们发出的网络请求',
    'privacy.li.3a': '<strong>模型下载。</strong>首次选择某个翻译模型时，扩展会从 Hugging Face 的 CDN（huggingface.co / hf.co）下载权重文件，并缓存到浏览器存储中以供离线使用。Hugging Face 可能会按标准 HTTP 请求记录你的 IP 地址。',
    'privacy.li.3b': '<strong>OCR Worker。</strong>当回落到 OCR 处理图片/视频内容时，扩展会从 <code>tessdata.projectnaptha.com</code> 下载 Tesseract.js 语言数据，并从 <code>cdn.jsdelivr.net</code> 下载一小段 WASM 二进制。这些是静态资源 CDN。',
    'privacy.li.3c': '<strong>授权校验（仅付费用户）。</strong>当你在弹窗中粘贴授权 key 时，扩展会把 key（且仅 key）发送到我们的 license 服务器。服务器返回 key 是否有效、属于哪个计划。这些请求的 IP 地址我们保存不超过 7 天；授权 key ID 和时间戳会保留用于反欺诈。',
    'privacy.h2.4': '4. 我们不收集',
    'privacy.li.4a': '你选定翻译的文字。',
    'privacy.li.4b': '你访问的页面。',
    'privacy.li.4c': '你的浏览历史。',
    'privacy.li.4d': '任何分析或埋点。扩展里没有 Google Analytics、Sentry、PostHog。',
    'privacy.li.4e': '表单数据、密码、Cookie，或你拉出的矩形以外的任何 DOM 内容。',
    'privacy.h2.5': '5. 支付数据',
    'privacy.p.5a': '如你购买付费档，付款由我们的 Merchant of Record <strong>Paddle.com Market Limited</strong> 处理。Paddle 直接处理你的卡信息、账单地址和税务信息 —— 我们看不到也不存储你的卡。Paddle 符合 GDPR 与 CCPA。详见 <a href="https://www.paddle.com/legal/privacy" target="_blank" rel="noopener">Paddle 的隐私政策</a>。',
    'privacy.p.5b': '我们从 Paddle 收到的是：你的邮箱、授权 key 标识、计划、购买日期。我们仅用这些数据 (a) 派发和校验你的授权 key，(b) 提供退款和支持，(c) 按法律要求保存税务记录。',
    'privacy.h2.6': '6. 你设备上的存储',
    'privacy.p.6a': '扩展会在 <code>chrome.storage.local</code>（你的浏览器、你的机器）中存储：',
    'privacy.li.6a': '你的 UI 偏好（选定语言、模型、字号）。',
    'privacy.li.6b': '若已激活，你的授权 key 与缓存的"最后校验时间"（用于离线宽限）。',
    'privacy.li.6c': '每个翻译模型的下载进度 / 就绪状态。',
    'privacy.p.6b': '可随时通过卸载扩展，或在 <code>chrome://extensions</code> 中清除扩展存储来清除这些数据。',
    'privacy.h2.7': '7. 权限及其用途',
    'privacy.li.7a': '<strong><code>&lt;all_urls&gt;</code></strong>：让"区域翻译"功能能在你选择的任意网站上工作。扩展不会自动读取任何页面，仅作用于你显式拉出的矩形。',
    'privacy.li.7b': '<strong><code>storage</code></strong>：在多个会话间记住你的设置和授权。',
    'privacy.li.7c': '<strong><code>activeTab</code> + <code>scripting</code></strong>：你点扩展按钮时注入区域选择浮层。',
    'privacy.li.7d': '<strong><code>contextMenus</code></strong>：添加"翻译区域"右键菜单项。',
    'privacy.li.7e': '<strong><code>offscreen</code></strong>：Chrome MV3 要求 AI 推理在 service worker 外运行（service worker 的内存上限跑不动模型文件）。',
    'privacy.h2.8': '8. 儿童',
    'privacy.p.8': 'PaneTrans 不面向 13 岁以下儿童。我们不会有意收集儿童的个人数据。',
    'privacy.h2.9': '9. 你的权利（GDPR / CCPA）',
    'privacy.p.9': '如你是欧盟/英国居民，你有权访问、更正、删除并导出我们保存的关于你的个人数据（本质上就是你的邮箱与授权 key）。加州居民在 CCPA 下享有类似权利。用付款邮箱发邮件到 <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> 即可行使这些权利。',
    'privacy.h2.10': '10. 变更',
    'privacy.p.10': '本政策的任何更新版本将发布在本页面，并更新"最后更新"日期。若变更对你的权利有重大影响，我们将通过邮件通知持有有效授权的用户。',
    'privacy.h2.11': '11. 联系',
    'privacy.p.11': '隐私或数据保护相关问题：<a href="mailto:hi@julineshang.win">hi@julineshang.win</a>。',

    // ---- refund ----
    'title.refund': '退款政策 — PaneTrans',
    'refund.h1': '退款政策',
    'refund.effective': '生效日期：2026-04-25 · 最后更新：2026-04-25',
    'refund.tldr': '<strong>14 天，无理由。</strong>购买后 14 天内若觉得 PaneTrans 不合适，用付款邮箱发邮件到 <a href="mailto:hi@julineshang.win">hi@julineshang.win</a>，我们全额退款。',
    'refund.h2.1': '1. 谁有资格',
    'refund.p.1': '任何在过去 14 天内购买 PaneTrans 付费档（终身或月付）的用户均可，不论你已使用 Pro 功能多少。',
    'refund.h2.2': '2. 怎么申请',
    'refund.li.2a': '用付款时的邮箱发邮件到 <a href="mailto:hi@julineshang.win">hi@julineshang.win</a>。',
    'refund.li.2b': '附上 Paddle 订单号（在 Paddle 给你发的收据邮件里）—— 没有也行，写上购买日期和大致金额即可。',
    'refund.li.2c': '不需要给理由。我们不会和你争。',
    'refund.h2.3': '3. 需要多久',
    'refund.p.3': '我们目标是 2 个工作日内回复确认，5 个工作日内处理退款。退款本身由 Paddle（我们的 Merchant of Record）签发，通常会在之后的 5–10 个工作日内回到你原支付方式。',
    'refund.h2.4': '4. 授权会怎么样',
    'refund.p.4': '退款发出后，你的授权 key 会被撤销。PaneTrans 免费档继续正常工作 —— 你只是失去对 LLM 级 Pro 模型的访问。',
    'refund.h2.5': '5. 订阅取消（月付）',
    'refund.p.5': '你可以随时在 Paddle 客户门户（链接在收据邮件里）直接取消月付订阅。取消会立即停止后续续费。当前付费周期会继续到到期日 —— 取消时不按比例退款。',
    'refund.h2.6': '6. 续费退款',
    'refund.p.6': '若月付订阅自动续费但你并不打算续，请在续费扣款 14 天内联系我们，会按上述同一个 14 天窗口退该笔续费。',
    'refund.h2.7': '7. 14 天窗口外',
    'refund.p.7': '14 天窗口之外的退款按个案处理。我们讲道理：如果 PaneTrans 在 Chrome 更新后挂了，或 Pro 模型因非你的原因停了，发邮件给我们，我们想办法解决。',
    'refund.h2.8': '8. Chargeback',
    'refund.p.8': '在向银行发起 chargeback 之前，请先邮件联系我们。Chargeback 对双方都是钱和时间的损失，我们更愿意直接退给你。多次 chargeback 可能导致授权被撤销且不再退款。',
    'refund.h2.9': '9. 联系',
    'refund.p.9': '退款请求和问题：<a href="mailto:hi@julineshang.win">hi@julineshang.win</a>。',
  },

  // ==========================================================================
  // 日本語 (ja-JP)
  // ==========================================================================
  ja: {
    // ---- Shared ----
    'nav.features': '機能',
    'nav.pricing': '料金',
    'footer.tagline': 'すべてのフレームに、明快な窓を。',
    'footer.product': 'プロダクト',
    'footer.legal': '規約・ポリシー',
    'footer.contact': 'お問い合わせ',
    'footer.legal.terms': '利用規約',
    'footer.legal.privacy': 'プライバシーポリシー',
    'footer.legal.refund': '返金ポリシー',
    'footer.copy': '© 2026 PaneTrans · Chrome 向けローカル AI 翻訳',
    'legal.canonicalNote': 'この日本語版は参考用です。法的拘束力を持つのは <a href="?lang=en">英語版</a> です。',

    // ---- index ----
    'title.index': 'PaneTrans — 画面領域をリアルタイム翻訳するローカル AI Chrome 拡張',
    'meta.index': '任意のウェブページで領域を選択すると、PaneTrans が半透明のポップアップを固定し、テキストが変わるたびにリアルタイム翻訳します。ローカル AI で動作 —— クラウド不要、API キー不要、ブラウザ外には何も出ません。',
    'og.title.index': 'PaneTrans — すべてのフレームに、明快な窓を',
    'og.desc.index': '領域を継続監視する、ローカル AI 駆動の Chrome 翻訳拡張。',
    'index.hero.h1': '画面の中の言葉に、明快な窓を。',
    'index.hero.lede': '任意のウェブページで矩形を描くだけ。PaneTrans が半透明のポップアップを固定し、<strong>リアルタイム翻訳</strong>でテキストが変わるたびに更新します —— ライブチャット、動画字幕、ティッカー、どこでも。',
    'index.hero.ledeSmall': '翻訳はすべてあなたのマシンでローカル実行。クラウドなし、API キーなし、ブラウザ外には何も出ません。',
    'index.cta.seePricing': '料金を見る',
    'index.cta.howItWorks': '仕組み',
    'index.features.h2': 'PaneTrans でできること',
    'index.feat1.h3': '囲って、見守る。',
    'index.feat1.p': 'どこでも右クリック → <em>領域を翻訳</em> → 矩形をドラッグ。ドラッグ可能なポップアップが原文と訳文を並べて表示します。',
    'index.feat2.h3': 'ずっと見続ける。',
    'index.feat2.p': '<code>MutationObserver</code> が矩形を追跡します。ライブチャット、字幕の変化、ティッカーの更新 —— ポップアップが自動で再翻訳します。ページの任意の部分にリアルタイム字幕の帯を貼り付ける感覚です。',
    'index.feat3.h3': '用途別に選べるローカル AI。',
    'index.feat3.p': '無料枠：<strong>OPUS-MT</strong>（約 160 MB/言語ペア、WebGPU でリアルタイム）と <strong>NLLB-200</strong> / <strong>M2M-100</strong> で品質向上。Pro 枠：LLM 級の <strong>gpt-oss</strong> と <strong>Gemma 3</strong> でより自然な出力。',
    'index.trust.h2': '外国語コンテンツを扱う人が PaneTrans を選ぶ理由',
    'index.trust.li1': '<strong>データ漏洩ゼロ。</strong>翻訳モデルはブラウザのキャッシュに保存。第三者サーバーへのリクエストなし。一度ダウンロードすればオフラインでも動作します。',
    'index.trust.li2': '<strong>単発ではなく持続的。</strong>多くの翻訳ツールは一度訳して終わり。PaneTrans は閉じるまで領域にポップアップを固定し続けます。',
    'index.trust.li3': '<strong>YouTube バイリンガル字幕</strong>を動画学習者向けの独立オプションとして提供。',
    'index.trust.li4': '<strong>オープンアーキテクチャ。</strong><a href="https://huggingface.co/docs/transformers.js" target="_blank" rel="noopener">Transformers.js</a> + <a href="https://huggingface.co/Xenova" target="_blank" rel="noopener">Xenova ONNX モデル</a>で構築。モデル一覧は <code>src/utils/languages.js</code> で確認できます。',
    'index.ctaBand.h2': '使ってみますか？',
    'index.ctaBand.p': '無料枠で 10 以上の言語のリアルタイム翻訳が利用可能。Pro 枠で LLM 級モデルを解放、より繊細な訳出が可能です。',
    'index.ctaBand.btn': '料金',

    // ---- pricing ----
    'title.pricing': '料金 — PaneTrans',
    'meta.pricing': 'PaneTrans の料金：10 以上の言語のリアルタイム翻訳は無料。$14.99 永続買い切り、または $2.99/月で LLM 級モデルを解放。',
    'pricing.h1': '料金',
    'pricing.lede': 'PaneTrans は 10 以上の言語のリアルタイム翻訳を無料で利用できます。Pro でより大きな LLM ベースのモデルを解放し、訳文の流暢さを高められます。',
    'pricing.free.h2': '無料',
    'pricing.free.priceSub': '永続無料',
    'pricing.free.li1': 'ドラッグ選択の領域翻訳、継続モード対応',
    'pricing.free.li2': 'YouTube バイリンガル字幕',
    'pricing.free.li3': 'OPUS-MT（160 MB · リアルタイム）',
    'pricing.free.li4': 'NLLB-200（6 億パラメータ）',
    'pricing.free.li5': 'M2M-100（4.18 億パラメータ）',
    'pricing.free.li6': '10 以上の言語、全方向の翻訳ペア',
    'pricing.free.li7': 'ローカル処理 —— データはブラウザ外に出ません',
    'pricing.free.cta': '無料インストール',
    'pricing.lifetime.badge': 'ベストバリュー',
    'pricing.lifetime.h2': '永続',
    'pricing.lifetime.priceSub': '一括払い · 永続',
    'pricing.lifetime.li1': '無料版のすべて',
    'pricing.lifetime.li2': '<strong>gpt-oss 1.5B</strong> —— LLM 級翻訳',
    'pricing.lifetime.li3': '<strong>Gemma 3（4B）</strong> —— 文脈を踏まえた自然さ',
    'pricing.lifetime.li4': 'メール優先サポート',
    'pricing.lifetime.li5': '将来のモデル更新もすべて含む',
    'pricing.lifetime.li6': 'ログインしているすべてのブラウザで利用可',
    'pricing.lifetime.cta': '永続版を購入 — $14.99',
    'pricing.lifetime.note': '14 日間、理由不要で返金。',
    'pricing.monthly.h2': '月額',
    'pricing.monthly.priceSub': 'いつでもキャンセル可',
    'pricing.monthly.li1': '無料版のすべて',
    'pricing.monthly.li2': '<strong>gpt-oss 1.5B</strong> —— LLM 級翻訳',
    'pricing.monthly.li3': '<strong>Gemma 3（4B）</strong> —— 文脈を踏まえた自然さ',
    'pricing.monthly.li4': 'メールサポート',
    'pricing.monthly.li5': 'いつでもキャンセル可、契約なし',
    'pricing.monthly.cta': '購読 — $2.99/月',
    'pricing.monthly.note': '初回課金から 14 日間返金可。',
    'pricing.faq.h2': 'よくある質問',
    'pricing.faq.q1': '支払いはどこに行くの？カード情報は安全？',
    'pricing.faq.a1': '支払いは Paddle.com が処理します。Paddle は Merchant of Record として 200 以上の国・地域で税務とコンプライアンスを担います。PaneTrans はカード情報を一切見ません —— データは Paddle の PCI 準拠インフラに保管されます。',
    'pricing.faq.q2': '永続版と月額の違いは？',
    'pricing.faq.a2': '永続版は $14.99 を一回払って恒久アクセス —— 将来のモデル更新もすべて含みます。月額は $2.99/月でいつでもキャンセル可。永続版は 5 ヶ月で元が取れます。',
    'pricing.faq.q3': '複数のパソコンで Pro を使える？',
    'pricing.faq.a3': '使えます。購入後にライセンスキーがメールで届きます。個人で使うブラウザならいくつでもアクティベートできます。',
    'pricing.faq.q4': '返金はどう？',
    'pricing.faq.a4': '14 日間、理由不要の返金枠です。<a href="mailto:hi@julineshang.win">hi@julineshang.win</a> に購入時のメールで連絡してください。詳細は <a href="refund.html">返金ポリシー</a> をご覧ください。',
    'pricing.faq.q5': 'PaneTrans は何かデータをサーバーに送る？',
    'pricing.faq.a5': '翻訳データはブラウザ外には出ません。発生するネットワークリクエストは：(1) 初回のモデルファイル取得（Hugging Face から）、(2) 有料プラン有効化時のライセンスキー検証だけです。いずれも <a href="privacy.html">プライバシーポリシー</a> に記載しています。',

    // ---- support ----
    'title.support': 'サポート — PaneTrans',
    'support.h1': 'サポート',
    'support.metaDate': '最終更新：2026-05-18',
    'support.tldr': 'お困りですか？<a href="mailto:hi@julineshang.win">hi@julineshang.win</a> 宛に Chrome のバージョン、問題が起きたページの URL、関連する場合は Paddle 注文 ID を添えてご連絡ください。営業日 2 日以内に返信します。',
    'support.quickStart.h2': 'クイックスタート',
    'support.quickStart.li1': 'Chrome ウェブストアから PaneTrans をインストール。',
    'support.quickStart.li2': '翻訳したいテキストがあるウェブページを開く。',
    'support.quickStart.li3': '右クリック → <strong>領域を翻訳</strong>、またはツールバーの PaneTrans アイコン → <strong>領域をドラッグ</strong>。',
    'support.quickStart.li4': 'テキストの周りに矩形をドラッグ。原文と訳文が並んだドラッグ可能なポップアップが現れます。',
    'support.quickStart.li5': '下のテキストが変わるたびにポップアップは再翻訳します —— 終わったら × で閉じてください。',
    'support.issues.h2': 'よくあるトラブル',
    'support.issue.slowFirst.h3': '最初の翻訳が遅い。',
    'support.issue.slowFirst.p': '初めて翻訳モデルを選んだとき、PaneTrans は Hugging Face の CDN からダウンロードします（OPUS-MT で約 160 MB、NLLB / M2M / Gemma はもっと大きい）。モデルはブラウザにキャッシュされるので、以降の翻訳は即座です。ツールバーポップアップ → <strong>モデル</strong> から事前ダウンロードもできます。',
    'support.issue.noTrans.h3': 'ポップアップに原文しか出ず訳が出ない。',
    'support.issue.noTrans.p': 'たいていは選んだモデルがまだダウンロード中か、マシンに WebGPU がないケースです。ツールバーポップアップ → <strong>モデル</strong> で進捗を確認してください。WebGPU が使えない場合、PaneTrans は WASM にフォールバックします（遅いですがどのマシンでも動きます）。',
    'support.issue.noMenu.h3': '右クリックに「領域を翻訳」がない。',
    'support.issue.noMenu.p': '<code>chrome://extensions</code> で拡張が有効か確認してください。インストール直後の場合、ページを一度再読み込み —— コンテキストメニュー項目はページ読み込み時に登録されます。',
    'support.issue.noYt.h3': 'YouTube のバイリンガル字幕が出ない。',
    'support.issue.noYt.p': 'ツールバーポップアップで <strong>YouTube 字幕</strong> をオンにしてから、YouTube タブを再読み込みしてください。本機能は <code>youtube.com/watch?v=…</code> ページでのみ有効です。',
    'support.issue.noOcr.h3': '画像 / 動画内の OCR が動かない。',
    'support.issue.noOcr.p': 'PaneTrans は OCR に Tesseract.js を使用します。初回利用時に <code>tessdata.projectnaptha.com</code> から言語データを取得します。ネットワークがそのホストをブロックしていると OCR は失敗します。ポップアップのエラーメッセージにどの言語データが必要かが表示されます。',
    'support.license.h2': 'ライセンスキー（Pro）',
    'support.license.notArrived.h3': 'Pro を購入したがライセンスキーが届かない。',
    'support.license.notArrived.p': 'Paddle からの領収メールが迷惑メールに入っていないか確認してください。ない場合、決済時のアドレスから連絡いただければ再送します。',
    'support.license.activate.h3': 'キーのアクティベート方法。',
    'support.license.activate.p': 'ツールバーポップアップ → <strong>アップグレード</strong> → キーを貼り付け → <strong>アクティベート</strong>。成功するとモデル選択に Pro モデル（gpt-oss、Gemma 3）が現れます。',
    'support.license.multi.h3': '複数のブラウザで Pro を使う。',
    'support.license.multi.p': 'キーは複数のブラウザでアクティベート可能です —— 同じ Chrome / Edge / Brave プロファイルでサインインし、それぞれでアクティベートしてください。上限に達したらメールでご連絡を、リセットします。',
    'support.license.refund.h3': '返金。',
    'support.license.refund.p': '14 日間、理由不要。手順の詳細は <a href="refund.html">返金ポリシー</a> をご覧ください。',
    'support.contact.h2': 'お問い合わせ',
    'support.contact.intro': 'メール：<a href="mailto:hi@julineshang.win">hi@julineshang.win</a><br>ご連絡の際は、以下を添えてください：',
    'support.contact.li1': 'Chrome / Edge / Brave のバージョン（<code>chrome://version</code> で確認）',
    'support.contact.li2': '問題が起きたページの URL（ウェブ関連の場合）',
    'support.contact.li3': 'ポップアップやエラーメッセージのスクリーンショット',
    'support.contact.li4': 'Paddle 注文 ID（ライセンス / 課金に関する場合）',
    'support.policies.h2': 'プライバシーとポリシー',

    // ---- terms ----
    'title.terms': '利用規約 — PaneTrans',
    'terms.h1': '利用規約',
    'terms.effective': '発効日：2026-04-25 · 最終更新：2026-04-25',
    'terms.h2.1': '1. 同意',
    'terms.p.1': 'PaneTrans ブラウザ拡張（「本サービス」）のインストールまたは利用をもって、本規約に同意したものとみなします。同意できない場合は、本サービスを利用しないでください。',
    'terms.h2.2': '2. 本サービスについて',
    'terms.p.2': 'PaneTrans は、ユーザーのブラウザ内で動作するローカル AI モデルを用いてウェブコンテンツを翻訳する Chrome ブラウザ拡張です。中核となる翻訳機能はすべてユーザーのデバイス上で動作します。',
    'terms.h2.3': '3. ライセンス',
    'terms.p.3': '本規約の遵守（および有料プランの場合は所定の料金の支払い）を条件として、当社は、個人非商用利用、または個人専門家としての自身の業務成果物の中での利用のために、本サービスをインストールし利用するための、個人的、非独占的、譲渡不可、取消可能なライセンスを付与します。',
    'terms.h2.4': '4. 有料機能',
    'terms.p.4a': '一部の機能（LLM 級の翻訳モデルなど）には有料ライセンスが必要です。有料ライセンスは以下のいずれかのプランで販売されます：',
    'terms.li.4a': '<strong>永続版：</strong>US$14.99 の一回払いで恒久利用。',
    'terms.li.4b': '<strong>月額：</strong>US$2.99/月の継続課金、次回更新前にいつでもキャンセル可。',
    'terms.p.4b': '支払いは Merchant of Record である Paddle.com Market Limited（「Paddle」）が処理します。取引自体には当社の規約に加え Paddle の規約も適用されます。',
    'terms.h2.5': '5. ライセンスキーとデバイス',
    'terms.p.5': '支払い成功後、ライセンスキーがメールで届きます。個人で使用するすべてのブラウザでアクティベートできます。ライセンスキーの他者との共有は禁止されており、違反した場合は返金なしにアクセスが取り消されることがあります。',
    'terms.h2.6': '6. 返金',
    'terms.p.6': '購入から 14 日以内であれば、支払いに使用したアドレスから <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> へメールにて全額返金を申請できます。詳細は <a href="refund.html">返金ポリシー</a> をご覧ください。',
    'terms.h2.7': '7. 利用上の制限',
    'terms.p.7a': '本サービスを以下の目的で使用しないことに同意します：',
    'terms.li.7a': 'アクセス権のないコンテンツの翻訳。',
    'terms.li.7b': 'オープンソース表示に反するリバースエンジニアリング、改変、または拡張コードの再配布。',
    'terms.li.7c': 'ライセンスキー検証システムの回避、または有料プランの不正利用。',
    'terms.li.7d': 'PaneTrans の翻訳を商用 API またはバッチサービスとして再販するためのインフラ上での運用。',
    'terms.h2.8': '8. モデルと第三者',
    'terms.p.8': '本サービスで使用される翻訳モデルは、初回利用時に Hugging Face からダウンロードされます。これらのモデルのライセンス（各モデルのライセンスはポップアップ UI に表示されます）の遵守はユーザーの責任です。PaneTrans は Hugging Face、OpenAI、Google、または各モデル作者と提携していません。',
    'terms.h2.9': '9. 免責',
    'terms.p.9': '本サービスは「現状のまま」「利用可能な範囲で」提供され、いかなる種類の保証もありません。翻訳品質は保証されません。翻訳が正確、完全、または特定の目的に適合することを保証するものではありません。法律、医療、金融、その他の重要な翻訳を PaneTrans のみに依存しないでください。',
    'terms.h2.10': '10. 責任の制限',
    'terms.p.10': '法律で許容される最大限において、本サービスから生じる、または本サービスに関連する当社の累積責任は、請求発生前 12 ヶ月間にあなたが本サービスに対して支払った金額を上限とします。間接的、付随的、または結果的損害について当社は責任を負いません。',
    'terms.h2.11': '11. 終了',
    'terms.p.11': '本規約（特に利用上の制限条項）に違反した場合、ライセンスを停止または取り消すことがあります。拡張機能をアンインストールすることで、いつでも本サービスの利用を停止できます。',
    'terms.h2.12': '12. 変更',
    'terms.p.12': '当社は本規約を更新することがあります。更新版はこのページに掲載し「最終更新」日付を更新します。重要な変更は、拡張機能のポップアップを通じて、または有効なライセンスをお持ちの場合はメールで通知します。',
    'terms.h2.13': '13. 準拠法',
    'terms.p.13': '本規約は、販売者の居住地（現在は中華人民共和国香港特別行政区）の法律に準拠し、抵触法の規則は適用しません。紛争は当該管轄区域の管轄裁判所で解決します。',
    'terms.h2.14': '14. 連絡先',
    'terms.p.14': '質問・通知：<a href="mailto:hi@julineshang.win">hi@julineshang.win</a>。',

    // ---- privacy ----
    'title.privacy': 'プライバシーポリシー — PaneTrans',
    'privacy.h1': 'プライバシーポリシー',
    'privacy.effective': '発効日：2026-04-25 · 最終更新：2026-04-25',
    'privacy.tldr': '<strong>要旨：</strong>PaneTrans はあなたが翻訳するテキストを収集・送信・保存しません。翻訳はすべてブラウザ内で完結します。拡張が行うネットワークリクエストは：(1) 初回のモデルファイル取得（Hugging Face）、(2) 有料プラン有効化時のライセンスキー検証（当社サーバー）のみです。',
    'privacy.h2.1': '1. 運営者',
    'privacy.p.1': '「PaneTrans」は、<a href="mailto:hi@julineshang.win">hi@julineshang.win</a> に登録した開発者の個人プロジェクトとして運営されています。本ポリシーは、PaneTrans 拡張のインストール、利用、または購入時に提供される情報の取り扱いを説明します。',
    'privacy.h2.2': '2. ローカル処理とサーバー処理',
    'privacy.p.2': '中核となる翻訳パイプライン —— テキスト抽出、モデル推論、OCR（動画フレームの光学文字認識）、翻訳ポップアップの描画 —— はすべて <a href="https://huggingface.co/docs/transformers.js" target="_blank" rel="noopener">Transformers.js</a> と ONNX モデルを用いてブラウザ内で動作します。<strong>翻訳するテキストがあなたのデバイスを離れることはありません。</strong>',
    'privacy.h2.3': '3. 当社が行うネットワークリクエスト',
    'privacy.li.3a': '<strong>モデルダウンロード。</strong>翻訳モデルを初めて選択すると、拡張は Hugging Face の CDN（huggingface.co / hf.co）から重みファイルをダウンロードし、オフライン利用のためにブラウザストレージにキャッシュします。Hugging Face は標準的な HTTP リクエストの一部として IP アドレスを記録することがあります。',
    'privacy.li.3b': '<strong>OCR ワーカー。</strong>画像 / 動画コンテンツへの OCR フォールバック時、拡張は <code>tessdata.projectnaptha.com</code> から Tesseract.js の言語データと、<code>cdn.jsdelivr.net</code> から小さな WASM バイナリをダウンロードします。これらは静的アセット CDN です。',
    'privacy.li.3c': '<strong>ライセンス検証（有料ユーザーのみ）。</strong>ポップアップにライセンスキーを貼り付けると、拡張はキー（およびキーのみ）を当社のライセンスサーバーに送信します。サーバーはキーの有効性と所属プランを返します。これらのリクエストの IP アドレスは 7 日を超えて記録しません。不正検知のためライセンスキー ID とタイムスタンプは記録します。',
    'privacy.h2.4': '4. 収集しないもの',
    'privacy.li.4a': '翻訳するために選択したテキスト。',
    'privacy.li.4b': 'あなたが訪問したページ。',
    'privacy.li.4c': '閲覧履歴。',
    'privacy.li.4d': '分析やテレメトリは一切なし。Google Analytics、Sentry、PostHog はいずれも組み込まれていません。',
    'privacy.li.4e': 'フォームデータ、パスワード、Cookie、あるいは明示的にドラッグした矩形外の DOM コンテンツ。',
    'privacy.h2.5': '5. 支払いデータ',
    'privacy.p.5a': '有料プラン購入時、支払いは当社の Merchant of Record である <strong>Paddle.com Market Limited</strong> が処理します。Paddle がカード情報、請求先住所、税務情報を直接扱います —— 当社はカード情報を見ず、保存もしません。Paddle は GDPR / CCPA に準拠しています。<a href="https://www.paddle.com/legal/privacy" target="_blank" rel="noopener">Paddle のプライバシーポリシー</a> を参照してください。',
    'privacy.p.5b': '当社が Paddle から受け取るのは：メールアドレス、ライセンスキー識別子、プラン、購入日です。これらは (a) ライセンスキーの発行と検証、(b) 返金とサポートの提供、(c) 法令で求められる税務記録の保管 にのみ使用します。',
    'privacy.h2.6': '6. 端末上のストレージ',
    'privacy.p.6a': '拡張は <code>chrome.storage.local</code>（あなたのブラウザ・あなたのマシン）に以下を保存します：',
    'privacy.li.6a': 'UI 設定（選択言語、モデル、フォントサイズ）。',
    'privacy.li.6b': '有効化済みのライセンスキーと、キャッシュされた「最終検証時刻」（オフライン猶予に使用）。',
    'privacy.li.6c': '各翻訳モデルのダウンロード進捗 / 準備状態。',
    'privacy.p.6b': '拡張をアンインストールするか、<code>chrome://extensions</code> から拡張ストレージをクリアすることで、いつでも削除できます。',
    'privacy.h2.7': '7. 権限と利用目的',
    'privacy.li.7a': '<strong><code>&lt;all_urls&gt;</code></strong>：領域翻訳機能をあなたが選んだ任意のサイトで動作させるために必要。拡張はページを自動で読みません。明示的にドラッグした矩形にのみ作用します。',
    'privacy.li.7b': '<strong><code>storage</code></strong>：セッションをまたいで設定とライセンスを記憶するため。',
    'privacy.li.7c': '<strong><code>activeTab</code> + <code>scripting</code></strong>：拡張ボタンを押したときに領域選択オーバーレイを注入するため。',
    'privacy.li.7d': '<strong><code>contextMenus</code></strong>：「領域を翻訳」を右クリックメニューに追加するため。',
    'privacy.li.7e': '<strong><code>offscreen</code></strong>：Chrome MV3 では Service Worker 外で AI 推論を行う必要があるため（Service Worker の メモリ上限はモデルファイルの読み込みに対応できません）。',
    'privacy.h2.8': '8. 子ども',
    'privacy.p.8': 'PaneTrans は 13 歳未満の子どもを対象としていません。子どもから故意に個人データを収集することはありません。',
    'privacy.h2.9': '9. あなたの権利（GDPR / CCPA）',
    'privacy.p.9': 'EU / UK 居住者は、当社が保有するあなたに関する個人データ（実質的にはメールとライセンスキー）への アクセス、訂正、削除、エクスポート を求める権利があります。カリフォルニア州居住者は CCPA に基づき同様の権利を有します。これらの権利の行使には、購入時のメールアドレスから <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> までご連絡ください。',
    'privacy.h2.10': '10. 変更',
    'privacy.p.10': '更新版はこのページに掲載し、「最終更新」日付を更新します。変更があなたの権利に重大な影響を与える場合、有効なライセンスをお持ちの方にはメールで通知します。',
    'privacy.h2.11': '11. 連絡先',
    'privacy.p.11': 'プライバシー・データ保護に関するご質問：<a href="mailto:hi@julineshang.win">hi@julineshang.win</a>。',

    // ---- refund ----
    'title.refund': '返金ポリシー — PaneTrans',
    'refund.h1': '返金ポリシー',
    'refund.effective': '発効日：2026-04-25 · 最終更新：2026-04-25',
    'refund.tldr': '<strong>14 日間、理由不要。</strong>購入から 14 日以内に PaneTrans が合わないと感じた場合、決済時のアドレスから <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> へご連絡いただければ全額返金します。',
    'refund.h2.1': '1. 対象者',
    'refund.p.1': 'PaneTrans の有料プラン（永続版または月額）を過去 14 日以内に購入した方は、Pro 機能をどれだけ使ったかに関わらず対象です。',
    'refund.h2.2': '2. 申請方法',
    'refund.li.2a': '決済時に使用したアドレスから <a href="mailto:hi@julineshang.win">hi@julineshang.win</a> へメール。',
    'refund.li.2b': 'お分かりであれば Paddle 注文 ID（Paddle の領収メールに記載）を添えてください。なければ購入日とおおよその金額で構いません。',
    'refund.li.2c': '理由は不要です。議論しません。',
    'refund.h2.3': '3. 所要時間',
    'refund.p.3': '営業日 2 日以内に受領確認、5 営業日以内に返金処理を目指します。返金自体は Merchant of Record である Paddle から発行され、通常その後 5〜10 営業日でお支払い元へ戻ります。',
    'refund.h2.4': '4. ライセンスの扱い',
    'refund.p.4': '返金発行と同時にライセンスキーは取り消されます。PaneTrans 無料枠は引き続き利用可能です —— 失われるのは LLM 級の Pro モデルへのアクセスのみです。',
    'refund.h2.5': '5. 月額のキャンセル',
    'refund.p.5': '月額購読は Paddle カスタマーポータル（領収メール内のリンク）からいつでもキャンセル可能です。キャンセルにより以降の自動更新は即停止します。現在の課金期間は期限まで継続 —— 解約時の日割り返金はありません。',
    'refund.h2.6': '6. 更新の返金',
    'refund.p.6': '月額が自動更新されたが意図せずだった場合、更新課金から 14 日以内に連絡いただければ、上記同じ 14 日枠で返金します。',
    'refund.h2.7': '7. 14 日を超える場合',
    'refund.p.7': '14 日枠を超える返金は個別対応です。Chrome 更新で PaneTrans が動かなくなった、Pro モデルがあなたのせいでなく停止した、などの場合はご相談ください。誠実に対応します。',
    'refund.h2.8': '8. チャージバック',
    'refund.p.8': '銀行へのチャージバック申請の前に、まずメールでご連絡ください。チャージバックは双方にとってお金と時間の損失で、私たちはまず返金を優先したいと考えます。繰り返しのチャージバックはライセンスの取消と以降の返金停止につながる場合があります。',
    'refund.h2.9': '9. 連絡先',
    'refund.p.9': '返金リクエスト・質問：<a href="mailto:hi@julineshang.win">hi@julineshang.win</a>。',
  },
};
